container:
  dockerfile: ci/cirrus.Dockerfile

env:
  EMAIL: cirrus@cirrus-ci.org

device_matrix_template: &DEVICE_MATRIX_TEMPLATE
  - env:
      DEVICE: --trezor-t
  - env:
      DEVICE: --trezor-1
  - env:
      DEVICE: --coldcard
  - env:
      DEVICE: --ledger
  - env:
      DEVICE: --bitbox01
  - env:
      DEVICE: --keepkey

lint_task:
  test_script:
    - flake8

basic_test_task:
  install_script:
    - poetry install
  matrix:
    - name: Type Check
      type_check_script: >
        poetry run
        mypy
        hwi.py
        hwilib/_base58.py
        hwilib/_bech32.py
        hwilib/_cli.py
        hwilib/commands.py
        hwilib/common.py
        hwilib/descriptor.py
        hwilib/devices/bitbox02.py
        hwilib/devices/coldcard.py
        hwilib/devices/digitalbitbox.py
        hwilib/devices/__init__.py
        hwilib/devices/keepkey.py
        hwilib/devices/ledger.py
        hwilib/devices/trezor.py
        hwilib/errors.py
        hwilib/_script.py
        hwilib/_serialize.py
        hwilib/tx.py
        hwilib/hwwclient.py
        hwilib/__init__.py
        hwilib/key.py
        hwilib/udevinstaller.py
    - name: Non-Device Tests
      test_script: cd test; poetry run ./run_tests.py; cd ..

wine_builder_task:
  container:
    dockerfile: contrib/build.Dockerfile
  build_script:
    - contrib/build_wine.sh
    - sha256sum dist/*

device_test_pipe:
  matrix:
    << : *DEVICE_MATRIX_TEMPLATE
  matrix:
    - env:
        INTERFACE: library
    - env:
        INTERFACE: cli
    - env:
        INTERFACE: library
  steps:
    - image: cirrus-ci-community/a9d9023c43a8c289d91bd16de9af4f40
      env:
        BUILD_BITCOIND: 1
      build_bitcoind_script: cd test && ./setup_environment.sh --bitcoind && cd ..
    - image: cirrus-ci-community/a9d9023c43a8c289d91bd16de9af4f40
      build_sim_script: cd test && ./setup_environment.sh $DEVICE && cd ..
    - image: cirrus-ci-community/a9d9023c43a8c289d91bd16de9af4f40
      install_script: poetry install
      test_script: cd test && poetry run ./run_tests.py $DEVICE --interface=$INTERFACE --device-only && cd ..
      on_failure:
        failed_script: tail -v -n +1 test/*.std*

dist_test_pipe:
  matrix:
    << : *DEVICE_MATRIX_TEMPLATE
  steps:
    - image: ci/cirrus.Dockerfile
      env:
        BUILD_BITCOIND: 1
      build_bitcoind_script: cd test && ./setup_environment.sh --bitcoind && cd ..
    - image: cirrus-ci-community/a9d9023c43a8c289d91bd16de9af4f40
      build_sim_script: cd test && ./setup_environment.sh $DEVICE && cd ..
    - image: cirrus-ci-community/7303893cf26ced54c171022ee7c89fc7
      build_dist_script:
        - contrib/build_bin.sh
        - contrib/build_dist.sh
        - sha256sum dist/*
  matrix:
    - steps:
      - image: cirrus-ci-community/a9d9023c43a8c289d91bd16de9af4f40
        name: $DEVICE Wheel
        install_script: pip install dist/*.whl
        test_script: cd test; ./run_tests.py $DEVICE --interface=cli --device-only; cd ..
        on_failure:
          failed_script: tail -v -n +1 test/*.std*
    - steps:
      - image: cirrus-ci-community/a9d9023c43a8c289d91bd16de9af4f40
        name: $DEVICE Sdist
        install_script: pip install $(find dist -name "*.tar.gz" -a -not -name "*amd64*")
        test_script: cd test; ./run_tests.py $DEVICE --interface=cli --device-only; cd ..
        on_failure:
          failed_script: tail -v -n +1 test/*.std*
    - steps:
      - image: cirrus-ci-community/a9d9023c43a8c289d91bd16de9af4f40
        name: $DEVICE Bindist
        install_script: poetry install
        test_script: cd test; poetry run ./run_tests.py $DEVICE --interface=bindist --device-only; cd ..
        on_failure:
          failed_script: tail -v -n +1 test/*.std*
